# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, lint and test

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        path: repo
        fetch-depth: 2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-${{ matrix.os }}-${{ matrix.node-version }}-
    - run: mkdir cypress-cache
    - run: yarn install --frozen-lockfile
      working-directory: repo
      env:
        CYPRESS_CACHE_FOLDER: ../cypress-cache
    - run: yarn build
      working-directory: repo
    - uses: actions/cache@v1
      id: build-cache
      with:
        path: repo
        key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ github.sha }}
    - uses: actions/cache@v1
      id: cypress-cache
      with:
        path: cypress-cache
        key: cypress-${{ matrix.os }}-${{ matrix.node-version }}-${{ github.sha }}

  lint:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/cache@v1
      id: restore-build
      with:
        path: '.'
        key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ github.sha }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn lint
      continue-on-error: true

  unit-test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/cache@v1
      id: restore-build
      with:
        path: '.'
        key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ github.sha }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn test:unit

  e2e-test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        node-version: [12.x]
        browser: [chrome, edge]
        exclude:
          - os: ubuntu-18.04
            browser: edge
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/cache@v1
      id: restore-build
      with:
        path: repo
        key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ github.sha }}
    - uses: actions/cache@v1
      id: restore-cypress
      with:
        path: cypress-cache
        key: cypress-${{ matrix.os }}-${{ matrix.node-version }}-${{ github.sha }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn cypress info
      working-directory: repo
      env:
        CYPRESS_CACHE_FOLDER: ../cypress-cache
    - run: yarn start-test start 3001 "cypress run --browser ${{ matrix.browser }}"
      working-directory: repo
      env:
        CYPRESS_CACHE_FOLDER: ../cypress-cache
    - uses: actions/cache@v1
      id: snapshots-cache
      with:
        path: repo/tests/e2e/snapshots
        key: snapshots-${{ matrix.os }}-${{ matrix.browser }}-${{ github.sha }}

  e2e-test-save-snapshots:
    needs: e2e-test
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        node-version: [12.x]
        browser: [chrome, edge]
        exclude:
          - os: ubuntu-18.04
            browser: edge
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/cache@v1
      id: restore-snapshots
      with:
        path: cache
        key: snapshots-${{ matrix.os }}-${{ matrix.browser }}-${{ github.sha }}
    - uses: actions/checkout@v2
      with:
        ref: snapshots
        path: repo
    - name: Copy snapshots
      run: |
        mkdir -p "repo/${SHA}/${OS}-${BROWSER}"
        cp -r cache/* "repo/${SHA}/${OS}-${BROWSER}/"
      env:
        SHA: ${{ github.sha }}
        OS: ${{ matrix.os }}
        BROWSER: ${{ matrix.browser }}
    - name: Save snapshots
      run: |
        git config --local user.email "example@example.com"
        git config --local user.name "${GITHUB_ACTOR}"
        git add .
        git commit -m "Add snapshots"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:snapshots
      working-directory: repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  e2e-test-check-diff:
    needs: e2e-test-save-snapshots
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [12.x]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/cache@v1
      id: restore-build
      with:
        path: repo
        key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ github.sha }}
    - uses: actions/checkout@v2
      with:
        ref: snapshots
        path: snapshots
    - name: Check diff
      run: |
        mkdir -p .reg
        cp -r ../snapshots/$(git rev-parse "HEAD") .reg/acutual
        cp -r ../snapshots/$(git rev-parse "HEAD^") .reg/expected
        yarn reg-cli .reg/actual .reg/expected .reg/diff -J .reg/reg.json -R .reg/report.html
      working-directory: repo
      continue-on-error: true
    - uses: actions/upload-artifact@v1
      with:
        name: snapshots-diff
        path: repo/.reg
